import {NextRequest,NextResponse} from "next/server"
import {appendSheetValues,clearAndWrite,getSheetRanges} from "@/lib/google-sheets"

const MASTER_ID="1fMxCSBRY8qtNfPU-eRASVo1vimnf8RSs0ADlPKjluOM"
const TAB="Dashboard Feedback"
const SUMMARY_TAB="Dashboard Feedback Summary"
const text=(v:unknown)=>String(v??"").trim()
function isoDate(v:unknown){if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const x=text(v);if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(/^\d{1,2}[/-]\d{1,2}[/-]\d{4}$/.test(x)){const[a,b,c]=x.split(/[/-]/);return`${c}-${b.padStart(2,"0")}-${a.padStart(2,"0")}`}return x}
const labels:Record<string,string>={external:"Faktor eksternal",promo:"Promo yang berjalan",bnpl:"BNPL",performance:"Performa staff",stock:"Ketersediaan stok"}
function normalize(raw:string){let clean=raw.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,"").replace(/\s+/g," ").trim();clean=clean.replace(/\s+([,.])/g,"$1").replace(/\.{2,}/g,".");return clean?clean.charAt(0).toUpperCase()+clean.slice(1).replace(/[.!?]?$/,"."):"Tidak ada detail tambahan."}
function professional(raw:string,category:string,name:string){return `${labels[category]??"Kondisi penjualan"}: berdasarkan feedback ${name}, ${normalize(raw)}`}
type Row={timestamp:string;date:string;staffId:string;name:string;category:string;raw:string;professional:string}
function mapRows(rows:unknown[][]):Row[]{return rows.map(r=>({timestamp:text(r[0]),date:isoDate(r[1]),staffId:text(r[2]),name:text(r[3]),category:text(r[4]),raw:text(r[5]),professional:text(r[6])})).filter(r=>r.date&&r.staffId)}
function summarize(rows:Row[]){const grouped=new Map<string,Row[]>();for(const row of rows){if(!grouped.has(row.date))grouped.set(row.date,[]);grouped.get(row.date)!.push(row)}return[...grouped.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,list])=>{const unique=[...new Map(list.map(x=>[x.staffId,x])).values()];const categories=[...new Set(unique.map(x=>labels[x.category]??x.category))];const details=unique.map(x=>x.professional||professional(x.raw,x.category,x.name));const summary=`Reason Store M118\n\n${details.join(" ")}\n\nFokus kendala: ${categories.join(", ")}.`;return[date,unique.length,summary,new Date().toISOString()]})}
async function readAll(email:string,key:string){const[rows]=await getSheetRanges(MASTER_ID,[`'${TAB}'!A2:G5000`],email,key);return mapRows(rows)}
async function syncSummary(all:Row[],email:string,key:string){const values=summarize(all);await clearAndWrite(MASTER_ID,`'${SUMMARY_TAB}'!A2:D5000`,`'${SUMMARY_TAB}'!A2`,values.length?values:[["","","",""]],email,key,"RAW")}

export async function GET(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({rows:[],summary:"",error:"Google Sheets belum tersambung"},{status:503});try{const all=await readAll(email,key);const period=req.nextUrl.searchParams.get("period")||"",date=req.nextUrl.searchParams.get("date")||"";const filtered=all.filter(r=>(!period||r.date.startsWith(period))&&(!date||r.date===date));const rows=[...new Map(filtered.map(x=>[`${x.date}:${x.staffId}`,x])).values()];const summaries=summarize(all);const summary=summaries.find(x=>x[0]===date)?.[2]||"";return NextResponse.json({rows,summary,storage:"MASTER DATA M118"})}catch(e){return NextResponse.json({rows:[],summary:"",error:e instanceof Error?e.message:"Gagal membaca feedback"},{status:500})}}

export async function POST(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum tersambung"},{status:503});try{const body=await req.json() as {date?:string;staffId?:string;name?:string;category?:string;feedback?:string};const date=isoDate(body.date),staffId=text(body.staffId),name=text(body.name),category=text(body.category),raw=text(body.feedback);if(!date||!staffId||!name||!category||!raw)return NextResponse.json({error:"Data feedback belum lengkap"},{status:400});const existing=await readAll(email,key);if(existing.some(r=>r.date===date&&r.staffId===staffId))return NextResponse.json({error:"Feedback staff ini untuk tanggal tersebut sudah tersimpan.",alreadySubmitted:true},{status:409});const timestamp=new Date().toISOString(),polished=professional(raw,category,name),saved={timestamp,date,staffId,name,category,raw,professional:polished};await appendSheetValues(MASTER_ID,`'${TAB}'!A:G`,[[timestamp,date,staffId,name,category,raw,polished]],email,key);await syncSummary([...existing,saved],email,key);return NextResponse.json({ok:true,...saved,storage:"MASTER DATA M118"})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal menyimpan feedback"},{status:500})}}
