"use client"

import {useCallback,useEffect,useMemo,useState} from "react"
import {BarChart3,Box,CalendarDays,ChevronDown,ChevronRight,ChevronUp,ClipboardCheck,Cloud,FileSpreadsheet,Gauge,Home,LayoutDashboard,Menu,MessageSquare,PackageSearch,RefreshCw,Settings,Target,TrendingUp,Users,WalletCards,X} from "lucide-react"
import {Progress} from "@/components/ui/progress"
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table"
import type {DailyMetric,M238Payload,StaffMetric} from "@/lib/m238-types"

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0})
const number=new Intl.NumberFormat("id-ID")
const percent=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`
const achievement=(value:number,target:number)=>target?value/target*100:0
const months=Array.from({length:12},(_,i)=>`2026-${String(i+1).padStart(2,"0")}`)
const monthName=(v:string)=>new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(`${v}-01T00:00:00`))

type PageKey="overview"|"daily"|"summary"|"staff"|"incentive"|"soh"|"stokan"|"lob"|"product"|"vas"|"mading"|"bnpl"|"check-spv"|"check-staff"|"feedback"|"cx"|"weekly"|"weekly-reason"|"settings"
type IconType=typeof Home
type NavItem={key:PageKey;label:string;icon:IconType}
type NavGroup={label:string;icon:IconType;items:NavItem[]}

const groups:NavGroup[]=[
  {label:"Dashboard",icon:LayoutDashboard,items:[{key:"overview",label:"Overview",icon:Home},{key:"daily",label:"Daily Sales",icon:TrendingUp},{key:"summary",label:"Daily Summary",icon:ClipboardCheck},{key:"staff",label:"Staff Performance",icon:Users},{key:"incentive",label:"Est. Incentive",icon:WalletCards},{key:"soh",label:"SOH",icon:PackageSearch},{key:"stokan",label:"Stokan",icon:Box}]},
  {label:"Target Fokus",icon:Gauge,items:[{key:"lob",label:"LOB Target Fokus",icon:Target},{key:"product",label:"Product Fokus 3PP",icon:Box},{key:"vas",label:"VAS Fokus",icon:Cloud}]},
  {label:"Administrasi",icon:ClipboardCheck,items:[{key:"mading",label:"Mading",icon:FileSpreadsheet},{key:"bnpl",label:"BNPL & Trade-In",icon:WalletCards},{key:"check-spv",label:"Checklist Store - SPV",icon:ClipboardCheck},{key:"check-staff",label:"Checklist Store - Staff",icon:ClipboardCheck}]},
  {label:"Reporting",icon:BarChart3,items:[{key:"feedback",label:"Feedback",icon:MessageSquare},{key:"cx",label:"NPS/CX & Member",icon:Users},{key:"weekly",label:"Weekly Report",icon:BarChart3},{key:"weekly-reason",label:"Weekly Reason",icon:MessageSquare}]},
  {label:"System",icon:Settings,items:[{key:"settings",label:"Settings",icon:Settings}]}
]
const labels=Object.fromEntries(groups.flatMap(group=>group.items.map(item=>[item.key,item.label]))) as Record<PageKey,string>

export default function Dashboard(){
  const[page,setPage]=useState<PageKey>("overview")
  const[period,setPeriod]=useState("2026-09")
  const[staffFilter,setStaffFilter]=useState("ALL")
  const[data,setData]=useState<M238Payload|null>(null)
  const[loading,setLoading]=useState(true)
  const[mobileOpen,setMobileOpen]=useState(false)
  const[openGroups,setOpenGroups]=useState<Record<string,boolean>>({Dashboard:true,"Target Fokus":true,Administrasi:true,Reporting:true,System:true})
  const load=useCallback(async(force=false)=>{setLoading(true);try{const suffix=force?`&refresh=1&t=${Date.now()}`:"";const response=await fetch(`/api/data?period=${period}${suffix}`,force?{cache:"no-store"}:undefined);setData(await response.json() as M238Payload)}finally{setLoading(false)}},[period])
  useEffect(()=>{let active=true;fetch(`/api/data?period=${period}`).then(response=>response.json()).then(payload=>{if(active)setData(payload as M238Payload)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[period])
  const open=(key:PageKey)=>{setPage(key);setMobileOpen(false)}
  const filteredStaff=useMemo(()=>data?.monthlyStaff.filter(row=>staffFilter==="ALL"||row.id===staffFilter)??[],[data,staffFilter])
  const updated=data?new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jakarta"}).format(new Date(data.generatedAt)):"—"
  return <div className="min-h-screen bg-[#f6f8fb] text-slate-900 lg:grid lg:grid-cols-[232px_minmax(0,1fr)]">
    {mobileOpen&&<button aria-label="Tutup menu" className="fixed inset-0 z-30 bg-slate-950/30 lg:hidden" onClick={()=>setMobileOpen(false)}/>} 
    <aside className={`${mobileOpen?"translate-x-0":"-translate-x-full"} fixed inset-y-0 left-0 z-40 w-[270px] border-r bg-white transition-transform lg:sticky lg:top-0 lg:h-screen lg:w-auto lg:translate-x-0`}>
      <div className="flex h-full flex-col overflow-y-auto p-4"><div className="flex items-center gap-3 border-b pb-5"><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-blue-600 to-slate-700 text-sm font-black text-white shadow-lg">M118</div><div className="min-w-0"><p className="font-extrabold leading-tight">Digimap PIM 3</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Performance Hub</p></div><button className="ml-auto rounded-lg p-2 lg:hidden" onClick={()=>setMobileOpen(false)}><X className="size-5"/></button></div>
        <nav className="mt-4 space-y-2">{groups.map(group=>{const GroupIcon=group.icon,expanded=openGroups[group.label];return <div key={group.label} className="rounded-2xl bg-slate-50/80 p-1"><button onClick={()=>setOpenGroups(v=>({...v,[group.label]:!expanded}))} className="flex w-full items-center gap-2 rounded-xl px-3 py-3 text-sm font-semibold text-slate-600 hover:bg-white"><GroupIcon className="size-4"/><span>{group.label}</span>{expanded?<ChevronUp className="ml-auto size-4"/>:<ChevronDown className="ml-auto size-4"/>}</button>{expanded&&<div className="space-y-1 pb-1">{group.items.map(item=>{const ItemIcon=item.icon;return <button key={item.key} onClick={()=>open(item.key)} className={`flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-sm transition ${page===item.key?"bg-white font-bold text-blue-700 shadow-sm ring-1 ring-slate-200":"text-slate-500 hover:bg-white"}`}><ItemIcon className="size-4"/><span>{item.label}</span></button>})}</div>}</div>})}</nav>
        <div className="mt-4 rounded-2xl border border-blue-100 bg-blue-50 p-3 text-xs leading-5 text-blue-800"><b>{data?.mode==="live"?"Master Sheet aktif":"Mode data contoh"}</b><br/>Pembaruan terakhir {updated}</div>
      </div>
    </aside>
    <main className="min-w-0 pb-12"><header className="sticky top-0 z-20 border-b bg-white/90 backdrop-blur-xl"><div className="flex h-16 items-center gap-3 px-4 sm:px-7"><button className="rounded-xl border p-2 lg:hidden" onClick={()=>setMobileOpen(true)}><Menu className="size-5"/></button><span className="text-sm font-semibold text-slate-400">M118</span><ChevronRight className="size-4 text-slate-300"/><b className="text-sm">{labels[page]}</b><button onClick={()=>void load(true)} className="ml-auto flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm font-semibold shadow-sm hover:bg-slate-50"><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/><span className="hidden sm:inline">Perbarui</span></button></div></header>
      <div className="px-4 pt-7 sm:px-7"><p className="text-[11px] font-bold uppercase tracking-[.22em] text-blue-600">M118 Performance Hub</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">{labels[page]}</h1><p className="mt-2 text-sm text-slate-500">Digimap APR Pondok Indah Mall 3</p></div>
      <div className="mt-6 space-y-5 px-4 sm:px-7">
        {page==="overview"&&<Overview data={data}/>} {page==="daily"&&<DailySales rows={data?.dailyStaff??[]} date={data?.latestDate??""}/>} {page==="summary"&&<><Filters period={period} setPeriod={setPeriod}/><Summary data={data}/></>}
        {page==="staff"&&<><Filters period={period} setPeriod={setPeriod} staff={staffFilter} setStaff={setStaffFilter} data={data}/><StaffPerformance rows={filteredStaff}/></>} {page==="incentive"&&<><Filters period={period} setPeriod={setPeriod}/><Incentive rows={data?.monthlyStaff??[]}/></>} {page==="soh"&&<Inventory/>} {page==="stokan"&&<Stokan/>}
        {page==="lob"&&<FocusPage title="LOB Target Fokus" items={[["MacBook",20,4],["iPhone",191,37],["iPad",65,5],["Apple Watch",17,2],["AirPods",24,5]]}/>} {page==="product"&&<FocusPage title="Product Fokus 3PP" items={[["Dino",200000000,0],["Hastag",150000000,0],["IGA",50000000,0],["iBacks",50000000,0]]} currency/>} {page==="vas"&&<FocusPage title="VAS Fokus" items={[["Qoala",500000000,27575001],["Telkomsel",400000000,10545000],["Indosat",50000000,0],["XL",150000000,898000]]} currency/>}
        {page==="mading"&&<InfoPage title="Mading" text="Ringkasan informasi store, promo, aktivitas, dan pengumuman untuk team M118."/>} {page==="bnpl"&&<InfoPage title="BNPL & Trade-In" text="Pencatatan harian BNPL dan Trade-In disiapkan mengikuti format dashboard M238."/>}
        {page==="check-spv"&&<Checklist role="SPV" href="https://forms.cloud.microsoft/pages/responsepage.aspx?id=iAw5Rakbn0eYpYaKADRxVqklIyFb72JDrV7GtVMqEcNUMUdNM1Q1VU4zTU9PTlpVTERHVUpZUk9BQS4u&route=shorturl"/>} {page==="check-staff"&&<Checklist role="Staff" href="https://forms.cloud.microsoft/pages/responsepage.aspx?id=iAw5Rakbn0eYpYaKADRxVqklIyFb72JDrV7GtVMqEcNUQVpVV1hBVTdHTDVDWVlMRkE0V0lRVDQySS4u&route=shorturl"/>}
        {page==="feedback"&&<InfoPage title="Feedback" text="Form feedback harian dan rangkuman store akan mengikuti data M118 pada master data."/>} {page==="cx"&&<InfoPage title="NPS/CX & Member" text="Monitoring CX, NPS, dan member per staff disiapkan untuk pencatatan harian."/>} {page==="weekly"&&<Weekly/>} {page==="weekly-reason"&&<InfoPage title="Weekly Reason" text="Reason per LOB, kendala, dan action plan mingguan dapat diperbarui berkala."/>} {page==="settings"&&<SettingsPage/>}
      </div>
    </main>
  </div>
}

function Card({label,value,sub,tone="blue",icon:Icon=TrendingUp}:{label:string;value:string;sub:string;tone?:"blue"|"green"|"amber"|"violet";icon?:IconType}){const c={blue:"bg-blue-50 text-blue-600",green:"bg-emerald-50 text-emerald-600",amber:"bg-amber-50 text-amber-600",violet:"bg-violet-50 text-violet-600"}[tone];return <article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><span className={`rounded-xl p-2.5 ${c}`}><Icon className="size-5"/></span></div><p className="mt-5 text-2xl font-black tracking-[-.04em]">{value}</p><p className="mt-4 border-t border-dashed pt-3 text-xs text-slate-500">{sub}</p></article>}
function SectionTitle({title,sub}:{title:string;sub:string}){return <div className="border-b px-5 py-4"><h2 className="font-extrabold">{title}</h2><p className="mt-1 text-sm text-slate-500">{sub}</p></div>}
function Empty({cols=12}:{cols?:number}){return <TableRow><TableCell colSpan={cols} className="h-28 text-center text-slate-400">Belum ada data pada filter ini.</TableCell></TableRow>}
function TableWrap({children}:{children:React.ReactNode}){return <div className="overflow-x-auto">{children}</div>}
function Filters({period,setPeriod,staff,setStaff,data}:{period:string;setPeriod:(v:string)=>void;staff?:string;setStaff?:(v:string)=>void;data?:M238Payload|null}){return <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="grid gap-4 sm:grid-cols-2 lg:max-w-2xl"><Filter label="Filter Bulan" value={period} onChange={setPeriod}>{months.map(x=><option key={x} value={x}>{monthName(x)}</option>)}</Filter>{staff!==undefined&&setStaff&&<Filter label="Filter Staff" value={staff} onChange={setStaff}><option value="ALL">Semua Staff</option>{data?.staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Filter>}</div></section>}
function Filter({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:React.ReactNode}){return <label><span className="mb-1.5 block text-xs font-bold uppercase tracking-wider text-slate-400">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-full rounded-xl border bg-white px-3 text-sm font-semibold outline-none focus:ring-2 focus:ring-blue-200">{children}</select></label>}

function Overview({data}:{data:M238Payload|null}){const d=data?.summary,t=data?.target,rows=[...(data?.monthlyStaff??[])].sort((a,b)=>b.amount-a.amount);if(!d||!t)return <Loading/>;return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Total Sales" value={money.format(d.amount)} sub={`Target ${money.format(t.amount)} · ${percent(achievement(d.amount,t.amount))}`} icon={TrendingUp}/><Card label="Device" value={money.format(d.device)} sub={`Target ${money.format(t.device)}`} icon={FileSpreadsheet}/><Card label="Accessories" value={money.format(d.accessories)} sub={`Target ${money.format(t.accessories)}`} tone="violet" icon={WalletCards}/><Card label="VAS" value={money.format(d.vas)} sub={`Target ${money.format(t.vas)}`} tone="green" icon={Cloud}/></section><section className="grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border bg-white shadow-sm"><SectionTitle title="Month Progress" sub="Progress target dan produktivitas transaksi."/><div className="grid grid-cols-2 gap-5 p-5 sm:grid-cols-3"><Stat label="Achievement" value={percent(achievement(d.amount,t.amount))}/><Stat label="Gap" value={money.format(Math.max(0,t.amount-d.amount))}/><Stat label="Month Pace" value={percent(d.timegone)}/><Stat label="UPT" value={d.upt.toFixed(1)}/><Stat label="ATV" value={money.format(d.atv)}/><Stat label="Transaction" value={number.format(d.invoices)}/></div></div><div className="rounded-2xl border bg-white shadow-sm"><SectionTitle title="Top Performance" sub="Peringkat berdasarkan sales bulan terpilih."/><div className="divide-y px-5">{rows.slice(0,3).map((row,i)=><div key={row.id} className="flex items-center gap-3 py-4"><span className="grid size-8 place-items-center rounded-full bg-slate-900 text-xs font-black text-white">{i+1}</span><div className="min-w-0 flex-1"><b>{row.name}</b><p className="text-xs text-slate-500">UPT {row.upt.toFixed(1)} · ATV {money.format(row.atv)}</p></div><b className="text-right">{money.format(row.amount)}</b></div>)}</div></div></section><StaffProductivity rows={rows}/><div className={`rounded-xl border px-4 py-3 text-sm ${data.mode==="live"?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>{data.mode==="live"?"Data live dari Master Dashboard SPW M118 2026.":"Data contoh ditampilkan karena sumber live belum tersedia."}</div></>}
function Stat({label,value}:{label:string;value:string}){return <div><p className="text-xs text-slate-400">{label}</p><p className="mt-1 font-black">{value}</p></div>}
function Loading(){return <div className="h-64 animate-pulse rounded-2xl bg-white"/>}
function DailySales({rows,date}:{rows:StaffMetric[];date:string}){const total=rows.reduce((a,r)=>({amount:a.amount+r.amount,acc:a.acc+r.accessories,vas:a.vas+r.vas,qty:a.qty+r.qty,inv:a.inv+r.invoices}),{amount:0,acc:0,vas:0,qty:0,inv:0});return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Sales Hari Ini" value={money.format(total.amount)} sub={`${number.format(total.inv)} invoice · ${number.format(total.qty)} unit`} icon={TrendingUp}/><Card label="Accessories" value={money.format(total.acc)} sub="Kontribusi accessories" tone="violet" icon={WalletCards}/><Card label="VAS" value={money.format(total.vas)} sub="Kontribusi VAS" tone="green" icon={Cloud}/><Card label="UPT / ATV" value={`${total.inv?(total.qty/total.inv).toFixed(1):"0.0"}`} sub={total.inv?money.format(total.amount/total.inv):money.format(0)} tone="amber" icon={Gauge}/></section><StaffProductivity rows={rows} title={`Daily Sales Staff · ${date||"Data terbaru"}`}/></>}
function Summary({data}:{data:M238Payload|null}){const d=data?.summary,t=data?.target;if(!d||!t)return <Loading/>;return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Target" value={money.format(t.amount)} sub={`${monthName(t.period)} · M118`} icon={Target}/><Card label="MTD Sales" value={money.format(d.amount)} sub={`${percent(achievement(d.amount,t.amount))} dari target`} tone="green"/><Card label="Variance" value={money.format(d.amount-t.amount)} sub="Selisih terhadap target bulan" tone="amber" icon={BarChart3}/><Card label="Estimasi" value={money.format(d.estimate)} sub={`Timegone ${percent(d.timegone)}`} tone="violet" icon={CalendarDays}/></section><PointBreakdown d={d} t={t}/><DailyStore rows={data?.daily??[]}/></>}
function PointBreakdown({d,t}:{d:M238Payload["summary"];t:M238Payload["target"]}){const items=[{label:"Device",value:achievement(d.device,t.device),point:Math.min(t.device?d.device/t.device*60:0,60),max:60},{label:"Accessories",value:achievement(d.accessories,t.accessories),point:Math.min(t.accessories?d.accessories/t.accessories*30:0,30),max:30},{label:"VAS",value:achievement(d.vas,t.vas),point:Math.min(t.vas?d.vas/t.vas*10:0,10),max:10}];return <section className="rounded-2xl border bg-white shadow-sm"><SectionTitle title="Achievement by Point" sub="Bobot Device 60 · Accessories 30 · VAS 10"/><div className="grid gap-5 p-5 md:grid-cols-3">{items.map(x=><div key={x.label}><div className="mb-2 flex justify-between text-sm"><b>{x.label}</b><span className="font-extrabold">{x.point.toFixed(2)} / {x.max}</span></div><Progress value={Math.min(x.value,100)} className="h-2.5"/><p className="mt-2 text-xs text-slate-500">Achievement {percent(x.value)}</p></div>)}</div></section>}
function StaffProductivity({rows,title="Staff Productivity"}:{rows:StaffMetric[];title?:string}){return <section className="rounded-2xl border bg-white shadow-sm"><SectionTitle title={title} sub="Ringkasan sales, transaksi, UPT, dan ATV per staff."/><TableWrap><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Staff</TableHead><TableHead className="text-right">Sales</TableHead><TableHead className="text-right">Trx</TableHead><TableHead className="text-right">Device</TableHead><TableHead className="text-right">Accessories</TableHead><TableHead className="text-right">VAS</TableHead><TableHead className="text-right">UPT</TableHead><TableHead className="text-right">ATV</TableHead></TableRow></TableHeader><TableBody>{rows.length?rows.map(r=><TableRow key={r.id}><TableCell><b className="block whitespace-nowrap">{r.name}</b><span className="text-xs text-slate-400">{r.id}</span></TableCell><TableCell className="text-right font-bold">{money.format(r.amount)}</TableCell><TableCell className="text-right">{r.invoices}</TableCell><TableCell className="text-right">{money.format(r.device)}</TableCell><TableCell className="text-right">{money.format(r.accessories)}</TableCell><TableCell className="text-right">{money.format(r.vas)}</TableCell><TableCell className="text-right font-bold">{r.upt.toFixed(1)}</TableCell><TableCell className="text-right">{money.format(r.atv)}</TableCell></TableRow>):<Empty cols={8}/>}</TableBody></Table></TableWrap></section>}
function StaffPerformance({rows}:{rows:StaffMetric[]}){return <section className="rounded-2xl border bg-white shadow-sm"><SectionTitle title="Staff Performance" sub="Target mengikuti persentase staff pada Config M118."/><TableWrap><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Staff</TableHead><TableHead className="text-right">Target</TableHead><TableHead className="text-right">Achievement</TableHead><TableHead className="text-right">Variance</TableHead><TableHead className="text-right">Ach. %</TableHead><TableHead className="text-right">UPT</TableHead></TableRow></TableHeader><TableBody>{rows.length?rows.map(r=><TableRow key={r.id}><TableCell><b>{r.name}</b><p className="text-xs text-slate-400">Target share {percent(r.share*100)}</p></TableCell><TableCell className="text-right">{money.format(r.targets.amount)}</TableCell><TableCell className="text-right font-bold">{money.format(r.amount)}</TableCell><TableCell className={`text-right font-semibold ${r.amount>=r.targets.amount?"text-emerald-600":"text-rose-600"}`}>{money.format(r.amount-r.targets.amount)}</TableCell><TableCell className="text-right">{percent(achievement(r.amount,r.targets.amount))}</TableCell><TableCell className="text-right font-bold">{r.upt.toFixed(1)}</TableCell></TableRow>):<Empty cols={6}/>}</TableBody></Table></TableWrap></section>}
function Incentive({rows}:{rows:StaffMetric[]}){return <section className="rounded-2xl border bg-white shadow-sm"><SectionTitle title="Estimasi Incentive Staff" sub="MacBook, iPhone, iPad, Apple Watch, Qoala, dan accessories."/><TableWrap><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Staff</TableHead><TableHead className="text-right">MacBook</TableHead><TableHead className="text-right">iPhone</TableHead><TableHead className="text-right">iPad</TableHead><TableHead className="text-right">Watch</TableHead><TableHead className="text-right">Qoala</TableHead><TableHead className="text-right">Accessories</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader><TableBody>{rows.length?rows.map(r=><TableRow key={r.id}><TableCell><b>{r.name}</b></TableCell><TableCell className="text-right">{money.format(r.incentive.mac)}</TableCell><TableCell className="text-right">{money.format(r.incentive.iphone)}</TableCell><TableCell className="text-right">{money.format(r.incentive.ipad)}</TableCell><TableCell className="text-right">{money.format(r.incentive.watch)}</TableCell><TableCell className="text-right">{money.format(r.incentive.qoala)}</TableCell><TableCell className="text-right">{money.format(r.incentive.accessories)}</TableCell><TableCell className="text-right font-black text-blue-700">{money.format(r.incentive.total)}</TableCell></TableRow>):<Empty cols={8}/>}</TableBody></Table></TableWrap></section>}
function DailyStore({rows}:{rows:DailyMetric[]}){return <section className="rounded-2xl border bg-white shadow-sm"><SectionTitle title="Daily Sales Store" sub="Total penjualan, transaksi, UPT, ATV, device, accessories, dan VAS per hari."/><TableWrap><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Tanggal</TableHead><TableHead className="text-right">Total Sales</TableHead><TableHead className="text-right">Device</TableHead><TableHead className="text-right">Accessories</TableHead><TableHead className="text-right">VAS</TableHead><TableHead className="text-right">Invoice</TableHead><TableHead className="text-right">Qty</TableHead><TableHead className="text-right">UPT</TableHead><TableHead className="text-right">ATV</TableHead></TableRow></TableHeader><TableBody>{rows.length?rows.map(r=><TableRow key={r.date}><TableCell className="whitespace-nowrap font-bold">{r.date}</TableCell><TableCell className="text-right font-bold">{money.format(r.amount)}</TableCell><TableCell className="text-right">{money.format(r.device)}</TableCell><TableCell className="text-right">{money.format(r.accessories)}</TableCell><TableCell className="text-right">{money.format(r.vas)}</TableCell><TableCell className="text-right">{r.invoices}</TableCell><TableCell className="text-right">{r.qty}</TableCell><TableCell className="text-right">{r.upt.toFixed(1)}</TableCell><TableCell className="text-right">{money.format(r.atv)}</TableCell></TableRow>):<Empty cols={9}/>}</TableBody></Table></TableWrap></section>}

const inventory=[["APPMFYM4ID/A","iPhone 17 Pro Max 256GB Silver",11,0],["APPMFYP4ID/A","iPhone 17 Pro Max 256GB Deep Blue",15,0],["APPMFYN4ID/A","iPhone 17 Pro Max 256GB Cosmic Orange",16,1],["APPMG8G4ID/A","iPhone 17 Pro 256GB Silver",5,3],["APPMG6J4ID/A","iPhone 17 256GB Black",8,1],["APPMTP03ID/A","iPhone 15 128GB Black",13,0]] as const
function Inventory(){return <section className="rounded-2xl border bg-white shadow-sm"><SectionTitle title="Stock On Hand" sub="Contoh data SOH M118 · pembaruan 25 Agustus 2026."/><TableWrap><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Article</TableHead><TableHead>Description</TableHead><TableHead className="text-right">SOH</TableHead><TableHead className="text-right">Unit Sold</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{inventory.map(row=><TableRow key={row[0]}><TableCell className="font-mono text-xs">{row[0]}</TableCell><TableCell className="font-semibold">{row[1]}</TableCell><TableCell className="text-right font-bold">{row[2]}</TableCell><TableCell className="text-right">{row[3]}</TableCell><TableCell><span className={`rounded-full px-2 py-1 text-xs font-bold ${row[2]<=3?"bg-rose-50 text-rose-700":"bg-emerald-50 text-emerald-700"}`}>{row[2]<=3?"Low Stock":"Available"}</span></TableCell></TableRow>)}</TableBody></Table></TableWrap></section>}
function Stokan(){return <><section className="grid gap-4 sm:grid-cols-3"><Card label="Total SKU Contoh" value="6" sub="SKU pada tampilan awal" icon={Box}/><Card label="Total SOH" value="68" sub="Unit tersedia" tone="green" icon={PackageSearch}/><Card label="Low Stock" value="0" sub="Batas ≤ 3 unit" tone="amber" icon={Gauge}/></section><Inventory/></>}
function FocusPage({title,items,currency=false}:{title:string;items:(readonly [string,number,number])[];currency?:boolean}){return <section className="rounded-2xl border bg-white shadow-sm"><SectionTitle title={title} sub="Target vs achievement berdasarkan data contoh M118."/><div className="space-y-5 p-5">{items.map(([name,target,actual])=>{const pct=achievement(actual,target);return <div key={name}><div className="mb-2 flex items-end justify-between gap-4"><div><b>{name}</b><p className="text-xs text-slate-500">Target {currency?money.format(target):number.format(target)} · Actual {currency?money.format(actual):number.format(actual)}</p></div><b>{percent(pct)}</b></div><Progress value={Math.min(pct,100)} className="h-2.5"/></div>})}</div></section>}
function InfoPage({title,text}:{title:string;text:string}){return <section className="rounded-2xl border bg-white p-6 shadow-sm"><span className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><FileSpreadsheet className="size-5"/></span><h2 className="mt-5 text-xl font-black">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{text}</p><div className="mt-6 rounded-xl border border-dashed bg-slate-50 p-5 text-sm text-slate-500">Struktur menu sudah tersedia dan siap menggunakan data M118 saat pembaruan berikutnya.</div></section>}
function Checklist({role,href}:{role:string;href:string}){return <section className="rounded-2xl border bg-white p-6 shadow-sm"><span className="grid size-11 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><ClipboardCheck className="size-5"/></span><h2 className="mt-5 text-xl font-black">Checklist Store - {role}</h2><p className="mt-2 text-sm text-slate-500">Buka formulir checklist resmi melalui tombol berikut.</p><a href={href} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">Buka Checklist {role}</a></section>}
function Weekly(){const rows=[["Accessories",146509000,84467700],["Devices",1475787000,1017402000],["VAS",68252750,39018001]] as const;return <section className="rounded-2xl border bg-white shadow-sm"><SectionTitle title="Week 8 Q4 vs Week 9 Q4" sub="Contoh weekly report M118 dari master dashboard."/><TableWrap><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>LOB</TableHead><TableHead className="text-right">Week 8</TableHead><TableHead className="text-right">Week 9</TableHead><TableHead className="text-right">Selisih</TableHead><TableHead className="text-right">Growth</TableHead></TableRow></TableHeader><TableBody>{rows.map(([name,prev,now])=><TableRow key={name}><TableCell className="font-bold">{name}</TableCell><TableCell className="text-right">{money.format(prev)}</TableCell><TableCell className="text-right">{money.format(now)}</TableCell><TableCell className="text-right text-rose-600">{money.format(now-prev)}</TableCell><TableCell className="text-right font-bold text-rose-600">{percent((now-prev)/prev*100)}</TableCell></TableRow>)}</TableBody></Table></TableWrap></section>}
function SettingsPage(){return <section className="rounded-2xl border bg-white shadow-sm"><SectionTitle title="Settings" sub="Sumber data dan status dashboard M118."/><div className="grid gap-4 p-5 sm:grid-cols-2"><Setting label="Store" value="M118 · Digimap APR Pondok Indah Mall 3"/><Setting label="Sumber Data Utama" value="Master Dashboard SPW M118 2026"/><Setting label="Periode Default" value="September 2026"/><Setting label="Akses Dashboard" value="Publik melalui link"/></div></section>}
function Setting({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 font-bold">{value}</p></div>}
