"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";

type Row={article:string;description:string;qty:number;soldQty:number;category:string};
const groups=[["IPHONE","iPhone"],["IPAD","iPad"],["MACBOOK","Mac"],["APPLE WATCH","Apple Watch"],["AIRPODS, PENCIL & KEYBOARD","AirPods, Pencil & Keyboard"]] as const;

export default function M118SohParity(){
 const[host,setHost]=useState<HTMLElement|null>(null),[activeView,setActiveView]=useState(false),[tab,setTab]=useState<(typeof groups)[number][0]>("IPHONE"),[q,setQ]=useState(""),[rows,setRows]=useState<Row[]>([]),[updated,setUpdated]=useState(""),[soldDate,setSoldDate]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/soh?q=${encodeURIComponent(q)}&t=${Date.now()}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal membaca SOH");setRows(j.rows||[]);setUpdated(j.updated||"");setSoldDate(j.soldDate||"")}catch(e){setRows([]);setError(e instanceof Error?e.message:"Gagal membaca SOH")}finally{setLoading(false)}},[q]);
 useEffect(()=>{const t=setTimeout(()=>void load(),180);return()=>clearTimeout(t)},[load]);
 useEffect(()=>{const apply=()=>{const main=document.querySelector("main.m118-main") as HTMLElement|null;if(!main)return;const crumb=main.querySelector("header b")?.textContent?.trim(),on=crumb==="SOH";setActiveView(on);const root=main.querySelector(":scope > .mt-5.px-4") as HTMLElement|null;if(root){let h=root.querySelector("[data-m118-soh-host]") as HTMLElement|null;if(!h){h=document.createElement("div");h.dataset.m118SohHost="1";root.appendChild(h)}setHost(h)}document.body.classList.toggle("m118-soh-active",on)};apply();const mo=new MutationObserver(()=>requestAnimationFrame(apply));mo.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>{mo.disconnect();document.body.classList.remove("m118-soh-active")}},[]);
 const filtered=useMemo(()=>rows.filter(r=>r.category===tab),[rows,tab]),total=filtered.reduce((a,r)=>a+r.qty,0),sold=filtered.reduce((a,r)=>a+r.soldQty,0),label=groups.find(([k])=>k===tab)?.[1]||tab;
 if(!host)return null;
 return <>{createPortal(<div style={{display:activeView?"block":"none"}} className="space-y-5"><div><h1 className="text-3xl font-black">Stock On Hand</h1><p className="mt-1 text-sm text-slate-500">SOH per kategori{updated?` • Update stock ${updated}`:""}{soldDate?` • Qty Sold ${soldDate}`:""}.</p></div><section className="rounded-2xl border bg-white p-4 shadow-sm"><input className="h-11 w-full rounded-xl border bg-white px-3" value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari Article atau Description..."/></section><section className="rounded-2xl border bg-white p-2 shadow-sm"><div className="flex gap-2 overflow-x-auto">{groups.map(([key,name])=><button key={key} onClick={()=>setTab(key)} className={`shrink-0 rounded-xl px-4 py-3 text-sm font-black ${tab===key?"bg-blue-600 text-white":"bg-slate-100 text-slate-600"}`}>{name}</button>)}</div></section><section className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="text-xl font-black">{label}</h2><p className="text-sm text-slate-500">Tampilan hanya kategori yang sedang dipilih.</p></div><div className="flex gap-2"><span className="rounded-xl bg-blue-50 px-3 py-2 text-sm font-black text-blue-700">SOH {total}</span><span className="rounded-xl bg-emerald-50 px-3 py-2 text-sm font-black text-emerald-700">Sold {sold}</span></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Article</th><th className="p-3 text-left">Description</th><th className="p-3 text-right">Qty SOH</th><th className="p-3 text-right">Qty Sold</th><th className="p-3 text-right">Balance View</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="p-8 text-center text-slate-400">Memuat SOH...</td></tr>:error?<tr><td colSpan={5} className="p-8 text-center text-rose-600">{error}</td></tr>:filtered.length?filtered.map(r=><tr className="border-t" key={`${r.article}-${r.description}`}><td className="p-3 font-bold">{r.article}</td><td className="p-3">{r.description}</td><td className="p-3 text-right font-black">{r.qty}</td><td className="p-3 text-right font-black text-emerald-600">{r.soldQty}</td><td className="p-3 text-right font-semibold">{Math.max(0,r.qty-r.soldQty)}</td></tr>):<tr><td colSpan={5} className="p-8 text-center text-slate-400">Tidak ada data pada kategori/filter ini.</td></tr>}</tbody><tfoot><tr className="border-t-2 bg-slate-50 font-black"><td className="p-3" colSpan={2}>TOTAL</td><td className="p-3 text-right">{total}</td><td className="p-3 text-right text-emerald-600">{sold}</td><td className="p-3 text-right">{Math.max(0,total-sold)}</td></tr></tfoot></table></div></section></div>,host)}<style jsx global>{`body.m118-soh-active .m118-main>.mt-5.px-4>*:not([data-m118-soh-host]){display:none!important}body.m118-soh-active [data-m118-soh-host]{display:block!important}`}</style></>;
}
