"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import {MessageSquareText,Users} from "lucide-react";

type View="feedback"|"cx";
type Staff={id:string;name:string;amount:number;targets:{amount:number}};
type Payload={period:string;monthlyStaff:Staff[]};
type Feedback={date:string;staffId:string;name:string;category:string;text:string};
type Cx={date:string;staffId:string;name:string;cx:number;member:number};
const period=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
const pct=(a:number,t:number)=>t?`${(a/t*100).toFixed(1)}%`:"0%";
const money=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v);
function getLocal<T>(key:string):T[]{try{return JSON.parse(localStorage.getItem(key)||"[]") as T[]}catch{return[]}}
function setLocal<T>(key:string,rows:T[]){localStorage.setItem(key,JSON.stringify(rows))}

export default function M118FeedbackCxParity(){
 const[host,setHost]=useState<HTMLElement|null>(null),[view,setView]=useState<View|null>(null),[data,setData]=useState<Payload|null>(null),[date,setDate]=useState(today()),[staffId,setStaffId]=useState(""),[category,setCategory]=useState("external"),[text,setText]=useState(""),[cx,setCx]=useState(0),[member,setMember]=useState(0),[feedback,setFeedback]=useState<Feedback[]>([]),[cxRows,setCxRows]=useState<Cx[]>([]),[message,setMessage]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch(`/api/data?period=${period()}`,{cache:"no-store"});if(r.ok)setData(await r.json())}catch{}},[]);
 useEffect(()=>{void load();setFeedback(getLocal<Feedback>("m118-feedback-local"));setCxRows(getLocal<Cx>("m118-cx-local"))},[load]);
 useEffect(()=>{const apply=()=>{const main=document.querySelector("main.m118-main") as HTMLElement|null;if(!main)return;const label=main.querySelector("header b")?.textContent?.trim(),next:View|null=label==="Feedback"?"feedback":label==="NPS/CX & Member"?"cx":null;setView(next);const root=main.querySelector(":scope > .mt-5.px-4") as HTMLElement|null;if(root){let h=root.querySelector("[data-m118-fcx-host]") as HTMLElement|null;if(!h){h=document.createElement("div");h.dataset.m118FcxHost="1";root.appendChild(h)}setHost(h)}document.body.classList.toggle("m118-fcx-active",Boolean(next))};apply();const mo=new MutationObserver(()=>requestAnimationFrame(apply));mo.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>{mo.disconnect();document.body.classList.remove("m118-fcx-active")}},[]);
 const staff=data?.monthlyStaff||[],person=staff.find(x=>x.id===staffId),feedbackToday=feedback.filter(x=>x.date===date),cxToday=cxRows.filter(x=>x.date===date);
 const saveFeedback=()=>{if(!person||!text.trim())return;const next=[...feedback.filter(x=>!(x.date===date&&x.staffId===person.id)),{date,staffId:person.id,name:person.name,category,text:text.trim()}];setFeedback(next);setLocal("m118-feedback-local",next);setText("");setMessage("Feedback tersimpan di perangkat ini (mode lokal).")};
 const saveCx=()=>{if(!person)return;const next=[...cxRows,{date,staffId:person.id,name:person.name,cx,member}];setCxRows(next);setLocal("m118-cx-local",next);setCx(0);setMember(0);setMessage("CX/Member tersimpan di perangkat ini (mode lokal).")};
 const feedbackView=<div className="space-y-5"><div><h1 className="text-3xl font-black">Feedback</h1><p className="mt-1 text-sm text-slate-500">Input reason staff dan review pencapaian M118.</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-800">Mode lokal sementara: data tersimpan hanya di browser perangkat ini sampai storage server M118 tersedia.</div><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-3"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-11 rounded-xl border px-3"/><select value={staffId} onChange={e=>setStaffId(e.target.value)} className="h-11 rounded-xl border px-3"><option value="">Pilih staff</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)} className="h-11 rounded-xl border px-3"><option value="external">Faktor External</option><option value="promo">Promo yang Berjalan</option><option value="bnpl">BNPL</option><option value="stock">Ketersediaan Stok</option><option value="performance">Performa Staff</option></select></div>{person&&<div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Sales</p><b className="mt-1 block">{money(person.amount)}</b></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Target</p><b className="mt-1 block">{money(person.targets.amount)}</b></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Achievement</p><b className="mt-1 block">{pct(person.amount,person.targets.amount)}</b></div></div>}<textarea rows={5} value={text} onChange={e=>setText(e.target.value)} className="mt-4 w-full rounded-xl border p-3" placeholder="Tuliskan kendala, kondisi customer, dan action plan…"/><div className="mt-3 flex justify-end"><button disabled={!person||!text.trim()} onClick={saveFeedback} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Simpan Feedback</button></div></section><section className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-extrabold">Feedback Tersimpan</h2><p className="mt-1 text-sm text-slate-500">{feedbackToday.length} feedback pada tanggal terpilih.</p></div><div className="divide-y">{feedbackToday.length?feedbackToday.map(x=><article key={`${x.date}-${x.staffId}`} className="p-5"><div className="flex items-center justify-between gap-3"><b>{x.name}</b><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{x.category}</span></div><p className="mt-3 text-sm leading-6 text-slate-600">{x.text}</p></article>):<p className="p-8 text-center text-sm text-slate-400">Belum ada feedback.</p>}</div></section></div>;
 const cxTotal=cxToday.reduce((a,x)=>a+x.cx,0),memberTotal=cxToday.reduce((a,x)=>a+x.member,0);
 const cxView=<div className="space-y-5"><div><h1 className="text-3xl font-black">NPS/CX & Member</h1><p className="mt-1 text-sm text-slate-500">Input harian dan histori per staff M118.</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-800">Mode lokal sementara: data tersimpan hanya di browser perangkat ini sampai storage server M118 tersedia.</div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border bg-white p-5 shadow-sm"><Users className="size-5 text-blue-600"/><p className="mt-3 text-sm text-slate-500">CX</p><p className="mt-2 text-3xl font-black">{cxTotal}</p></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><MessageSquareText className="size-5 text-emerald-600"/><p className="mt-3 text-sm text-slate-500">New Member</p><p className="mt-2 text-3xl font-black">{memberTotal}</p></article></div><section className="grid gap-5 xl:grid-cols-[.9fr_1.3fr]"><div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="space-y-4"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-11 w-full rounded-xl border px-3"/><select value={staffId} onChange={e=>setStaffId(e.target.value)} className="h-11 w-full rounded-xl border px-3"><option value="">Pilih staff</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><input type="number" min={0} value={cx} onChange={e=>setCx(Number(e.target.value))} className="h-11 rounded-xl border px-3" placeholder="CX"/><input type="number" min={0} value={member} onChange={e=>setMember(Number(e.target.value))} className="h-11 rounded-xl border px-3" placeholder="Member"/></div><button disabled={!person} onClick={saveCx} className="w-full rounded-xl bg-blue-600 px-4 py-3 font-bold text-white disabled:opacity-50">Simpan</button></div></div><div className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-extrabold">List Harian</h2><p className="text-sm text-slate-500">CX dan New Member.</p></div><div className="divide-y">{cxToday.map((r,i)=><div key={`${r.staffId}-${i}`} className="grid grid-cols-[1fr_auto_auto] gap-4 p-4"><b>{r.name}</b><span>CX {r.cx}</span><span>Member {r.member}</span></div>)}</div></div></section></div>;
 if(!host)return null;return <>{createPortal(<div style={{display:view?"block":"none"}}>{view==="feedback"?feedbackView:view==="cx"?cxView:null}{message&&<div className="fixed bottom-5 right-5 z-[100] rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white shadow-xl" onClick={()=>setMessage("")}>{message}</div>}</div>,host)}<style jsx global>{`body.m118-fcx-active .m118-main>.mt-5.px-4>*:not([data-m118-fcx-host]){display:none!important}body.m118-fcx-active [data-m118-fcx-host]{display:block!important}`}</style></>;
}
